## **线性代数基础**

### 线性代数基础基于Python的实现

---
---
#### 矩阵的创建

##### 直接定义

`np.array(参数)  `  
参数：**二维列表或者元组**

In [36]:
import numpy as np
A=[[1,2,3],[4,5,6],[7,8,9]] #列表
B=((1,2,3),(4,5,6),(7,8,9)) #元组
arrA=np.array(A)
arrB=np.array(B)
print("arrA=\n{}".format(arrA))
print("arrB=\n{}".format(arrB))

arrA=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arrB=
[[1 2 3]
 [4 5 6]
 [7 8 9]]


矩阵信息的获取  
行数和列数：`shape`属性或者`np.shape(参数)  `  
参数：**矩阵**  
  
类型:`type()`

In [37]:
print("A的属性：{}".format(type(A)))
print("arrA的属性:{}".format(type(arrA)))
print("arrA的大小：{}".format(arrA.shape))
print("arrA的大小：{}".format(np.shape(arrA)))

A的属性：<class 'list'>
arrA的属性:<class 'numpy.ndarray'>
arrA的大小：(3, 3)
arrA的大小：(3, 3)


以表格形式显示矩阵的内容  
`pd.DataFrame(matrix)`

In [38]:
import numpy as np 
import pandas as pd
pd.DataFrame(arrA)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

---
##### 间接创建

随机生成矩阵元素
1. `np.random.random(参数)  `  
参数：**元组**  
若元组为(d0,d1,...,dn)，则生成$\left [ 0,1 \right )$区间的$n$为维浮点~~数组~~矩阵；  
若元组为(d0,d1)，则生成$\text{d0} \times \text{d1}$阶矩阵  
2. `np.random.randint(low, high=None, size=None, dtype='I')`  
- 若`high=None`，则生成随机数范围是$\left [ 0,\text{low}  \right ) $  
否则范围是$\left [ \text{low},\text{high}  \right )$  
- `size=[d0,d1]`，则生成$\text{d0}\times\text{d1}$阶的矩阵
- `dtype`为数据类型，默认为np.int
 

In [39]:
import numpy as np

ranA= np.random.random((1,2,3))
ranB= np.random.random((3,3))
print(ranA)
print(ranB)

ranC= np.random.randint(low=30, high=648, size=[3,3], dtype='I')
print(ranC)

[[[0.86506395 0.69897602 0.54097832]
  [0.74527431 0.80395849 0.08592888]]]
[[0.69990184 0.52253652 0.96460442]
 [0.45816972 0.1869911  0.52582338]
 [0.54926951 0.97283471 0.08056014]]
[[475 188 239]
 [524 325 263]
 [580 127 209]]


改变矩阵的大小  
`reshape(参数)`  
参数：一个正整数的元组`（行数，列数）`,元组的括号可以省略    
若行数或者列数中有一个 **-1**，该函数则会自动根据另一个参数计算出 **-1** 的具体数值

In [40]:
newA=arrA.reshape((3,-1))
print(newA)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


---
##### 矩阵元素的存取操作

取整行`arr[i,:]` 其中 **,:** 可以省略  
取整列`arr[:,j]` 其中 **:,** 不可以省略
- 范围选取：例如要选取第0行到第1行(可以理解为$\left [ 0,2  \right ) $)`arr[0:2,:]`
- 特定行/列选取：例如要选取第0行跟第2行`arr[[0,2],:]`

In [41]:
print("arrA的第0行元素:\n{}".format(arrA[0,:]))
print("arrA的第2列元素:\n{}".format(arrA[:,2]))

print("arrA的第0到1行元素:\n{}".format(arrA[0:2,:]))
print("arrA的第0和2行元素:\n{}".format(arrA[[0,2],:]))

arrA的第0行元素:
[1 2 3]
arrA的第2列元素:
[3 6 9]
arrA的第0到1行元素:
[[1 2 3]
 [4 5 6]]
arrA的第0和2行元素:
[[1 2 3]
 [7 8 9]]


---
##### Numpy相关函数

1. 等差数列： `np.arange(start, stop, step, dtype=None)`  
范围：$\left [ \text{start} ,\text{stop}  \right ) $  
步长：step  
输出：**一维数组**，最好再转化为向量或者矩阵

In [69]:
import numpy as np
A= np.arange(0, 10, 1)
print("A={}".format(A))

A=[0 1 2 3 4 5 6 7 8 9]


2. 等差数列： `np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)`  
范围：$\left [ \text{start} ,\text{stop}  \right ] $  
若`endpoint=False`，则范围变为 $\left [ \text{start} ,\text{stop}  \right ) $  
数组长度：`num`  
输出：**一维数组**  
返回步长：`retstep=True`  


In [70]:
import numpy as np 
A= np.linspace(0, 10, 10, False, True)
print("A={}\nstep={}".format(A[0],A[1]))

A=[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
step=1.0


3. 等比序列：`np.logspace(start, stop, num=50, endpoint=True, base=10, dtype=None)`  
范围：$\left [ \text{start} ,\text{stop}  \right ] $  
若`endpoint=False`，则范围变为 $\left [ \text{start} ,\text{stop}  \right ) $  
数组长度：`num`  
输出：**一维数组**  
指数：`base`  

In [78]:
import numpy as np
A= np.logspace(1,10,10,base=2)
print("A={}".format(A))

A=[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


4. 计算数组的最大值、最小值、和、平均值、中值  

|参数`axis`|默认（整个矩阵）|列方向|行方向|
|:---:|:---:|:---:|:---:|
|取值|None|0|1|

最大值：`matrix.max(axis)`  
最小值：`matrix.min(axis)`  
最值的位置：`matrix.argmax(axis)`  
和：`matrix.sum(axis)`  
平均值：`matrix.mean(axis)`  
中值：`np.median(matrix, axis)`  

In [ ]:
#ex 5.2

---
---
#### 向量的创建

用创建矩阵的方式来创建向量

---
---
#### 特殊矩阵

##### 零矩阵

`np.zeros(参数)`  
参数： **元组**`(行数,列数)`

In [42]:
import numpy as np
arr0= np.zeros((3,3))
print("arr0=\n{}".format(arr0))

arr0=
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


---
##### 方阵

行列数相等的矩阵

---
##### 单位矩阵

1. `np.eye(参数)`  
参数：**行列数**  
2. `np.identity(参数)`  
参数：**行列数**


In [43]:
import numpy as np
E1= np.eye(3)
E2= np.identity(3)
print("E1=\n{}".format(E1))
print("E2=\n{}".format(E2))

E1=
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
E2=
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


---
##### 对角矩阵

1. 创建对角矩阵或获取对角线元素  
`np.diag(参数)`  
参数：
- 创建对角矩阵：**对角线元素**，以元组或者列表的形式
- 获取对角线元素：**方阵或矩阵**
2. 根据已有矩阵的对角线元素生成对角矩阵  
`np.diag(np.diag(参数))`  
参数:**方阵**

In [44]:
import numpy as np

#1.1
a=[1, 2, 3]
arr_diag1= np.diag(a)
print("arr_diag1=\n{}".format(arr_diag1))

#1.2
arr_diag2= np.diag(arrA)
print("arr_diag2=\n{}".format(arr_diag2))

#2
arr_diag3= np.diag(np.diag(arrA))
print("arr_diag3=\n{}".format(arr_diag3))

arr_diag1=
[[1 0 0]
 [0 2 0]
 [0 0 3]]
arr_diag2=
[1 5 9]
arr_diag3=
[[1 0 0]
 [0 5 0]
 [0 0 9]]


---
##### 上三角矩阵

`np.triu(matrix, k)`  
- **matrix**：矩阵  
- **k**：类型  

|k|结果|
|:---:|:---:|
|0|含对角线|
|1|不含对角线|

In [45]:
import numpy as np
arr_u1= np.triu(arrA, 0)
arr_u2= np.triu(arrA, 1)
print("arr_u1=\n{}".format(arr_u1))
print("arr_u2=\n{}".format(arr_u2))

arr_u1=
[[1 2 3]
 [0 5 6]
 [0 0 9]]
arr_u2=
[[0 2 3]
 [0 0 6]
 [0 0 0]]


---
##### 下三角矩阵

`np.tril(matrix, k)`  
- **matrix**：矩阵  
- **k**：类型  

|k|结果|
|:---:|:---:|
|0|含对角线|
|-1|不含对角线|

In [46]:
import numpy as np
arr_l1= np.tril(arrA, 0)
arr_l2= np.tril(arrA, -1)
print("arr_l1=\n{}".format(arr_l1))
print("arr_l2=\n{}".format(arr_l2))

arr_l1=
[[1 0 0]
 [4 5 0]
 [7 8 9]]
arr_l2=
[[0 0 0]
 [4 0 0]
 [7 8 0]]


---
##### 对称矩阵

关于主对角线对称的矩阵

1. 创建对称矩阵：利用上三角矩阵

In [47]:
import numpy as np
arr_sym= np.triu(arrA, 1)+ np.triu(arrA, 0).T
print("arr_sym=\n{}".format(arr_sym))

arr_sym=
[[1 2 3]
 [2 5 6]
 [3 6 9]]


2. 对称矩阵的判定：利用矩阵相等

In [48]:
import numpy as np
print("arrA是否为对称矩阵：{}".format(np.allclose(arrA,arrA.T)))

arrA是否为对称矩阵：False


---
##### 同型矩阵

行数和列数都相等的两个矩阵

---
##### 矩阵相等

两个矩阵行列数相等且对应位置的元素都一样  
`np.allclose(matrix1, matrix2)`

In [49]:
import numpy as np
print("arrA与arrB是否相等：{}".format(np.allclose(arrA, arrB)))

arrA与arrB是否相等：True


---
---
#### 矩阵的基本操作

---
##### 矩阵的加减法运算

运算前先判断是否为同型矩阵

---
##### 矩阵的数乘运算

$$\lambda \cdot \bf A=\bf A \cdot  \lambda =\begin{bmatrix}
  \lambda a_{11} & \lambda a_{12} & \cdots & \lambda a_{1n} \\
  \lambda a_{21} & \lambda a_{22} & \cdots & \lambda a_{2n} \\
  \vdots  & \vdots &  & \vdots \\
  \lambda a_{m1} & \lambda a_{m2} & \cdots & \lambda a_{mn} 
\end{bmatrix}$$

---
##### 矩阵的乘法

1. array类型
- `np.dot(matrix1, matrix2)`
- `matrix1.dot(matrix2)`
- `np.matmul(matrix1, matrix2)`  

2. array类型：两个同型矩阵中对应元素的相乘
- `np.multiply(matrix1, matrix2)`
- `matrix1 * matrix2`

3. matrix类型
- 前三种跟array类型一样
- `matrix1 * matrix2`

4. matrix类型：两个同型矩阵中对应元素的相乘
- 跟array类型的对应相乘的第一种一样

In [50]:
import numpy as np

matA= np.matrix(arrA)
matB= np.matrix(arrB)

print("matrix类型是矩阵乘法：\n{}\n*\n{}\n=\n{}".format(matA,matB,matA*matB))
print("array类型是对应元素相乘：\n{}\n*\n{}\n=\n{}".format(arrA,arrB,arrA*arrB))

matrix类型是矩阵乘法：
[[1 2 3]
 [4 5 6]
 [7 8 9]]
*
[[1 2 3]
 [4 5 6]
 [7 8 9]]
=
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
array类型是对应元素相乘：
[[1 2 3]
 [4 5 6]
 [7 8 9]]
*
[[1 2 3]
 [4 5 6]
 [7 8 9]]
=
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


---
##### 矩阵与向量的乘法

注意行列数的规范  
$$\bf {A}_{mn} \times {a}_{n1}=b_{m1}$$
$$\bf a_{1m} \times A_{mn}=b_{1n}$$

---
##### 矩阵的乘方

**只有方阵才能进行矩阵的乘方运算**

1. array类型  
- 多次`np.dot(matrix1, matrix2)`  
Tips: `matrix**n` 得到每个元素的n次方，所以不要求是方阵

2. matrix类型
- `matrix**n`

In [51]:
import numpy as np

print("arrA的2次方：\n{}".format(arrA.dot(arrA)))
print("arrA中所有元素的2次方：\n{}".format(arrA**2))
print("matA的2次方：\n{}".format(matA**2))

arrA的2次方：
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
arrA中所有元素的2次方：
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
matA的2次方：
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


---
---
#### 转置矩阵和逆矩阵

##### 转置矩阵

- `np.transpose(matrix)`
- `matrix.T`

In [52]:
import numpy as np
print("方法一：\n{}".format(np.transpose(arrA)))
print("方法二：\n{}".format(arrA.T))

方法一：
[[1 4 7]
 [2 5 8]
 [3 6 9]]
方法二：
[[1 4 7]
 [2 5 8]
 [3 6 9]]


---
##### 逆矩阵

1. array类型  
- `np.linalg.inv(matrix)`

2. matrix类型
- `matrix.I`

In [53]:
import numpy as np
print("inv()：\n{}".format(np.linalg.inv(arrA)))
print("I属性：\n{}".format(np.matrix(arrA).I))

inv()：
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
I属性：
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


---
---
#### 行列式

##### 行列式的计算

`np.linalg.det(matrix)`

In [54]:
import numpy as np 

print("det(arrA)：\n{}".format(np.linalg.det(arrA)))

det(arrA)：
6.66133814775094e-16


---
---
#### 秩

##### 矩阵秩的计算

`np.linalg.matrix_rank(matrix)`

In [55]:
print("matA的秩：\n{}".format(np.linalg.matrix_rank(matA)))

matA的秩：
2


---
---
#### 内积与正交

##### 向量的内积

$$\bf a_{1n} \cdot b_{n1}$$

`np.dot(vector1,vector2)`

In [56]:
import numpy as np
vec1= arrA[:,0]
vec2= arrA[0,:]
print("{} * {}.T = {}".format(vec1,vec2,vec1.dot(vec2)))

[1 4 7] * [1 2 3].T = 30


---
##### 向量的长度

`np.linalg.norm(vector)`

In [57]:
import numpy as np
print("||vec1||={}".format(np.linalg.norm(vec1)))

||vec1||=8.12403840463596


利用向量的内积和长度求两个向量夹角的余弦值  
$$\cos \theta =\frac{[\vec{x},\vec{y}]}{\left \| \vec{x} \right \| \times \left \| \vec{y} \right \| } $$

---
##### 向量的正交

向量相互垂直，即内积为0

---
##### 标准正交基

线性无关且向量两两垂直

对原浮点数进行四舍五入： `np.round(matrix, 0)`

---
---
---
### 应用

##### ex 5.2  
编号为1~4的4个学生选修了A~E共5门课，每个学生每门课的成绩对应下表。
|编号|A|B|C|D|E|
|:---:|:---:|:---:|:---:|:---:|:---:|
|1|80|75|75|78|83|
|2|98|70|85|84|90|
|3|90|75|90|90|95|
|4|88|70|82|80|82|  

求每个学生的平均分、最高分和最低分以及每门课的平均分、最高分和最低分。并且求出每门课的分数分布情况。

In [58]:
import numpy as np
import sympy

A=np.array([[80,75,75,78,83],[98,70,85,84,90],[90,75,90,90,95],[88,70,82,80,82]])
mean=list(sympy.symbols('mean:{}'.format(len(A))))
max=list(sympy.symbols('max:{}'.format(len(A))))
min=list(sympy.symbols('min:{}'.format(len(A))))
#每个学生的平均分
for i in range(len(A)):
    sum= 0
    Amax=A[i,0]
    Amin=A[i,0]
    for j in range(len(A[i])):
        sum+= A[i,j]/len(A[i])
        if A[i,j] > Amax:
            Amax=A[i,j]
        elif A[i,j] < Amin:
            Amin=A[i,j]
    mean[i]=sum
    max[i]=Amax
    min[i]=Amin
pl=[print("同学{}的平均分：{}，最高分：{}，最低分：{}".format((i+1), mean[i], max[i], min[i])) for i in range(len(A))]
print()

#每门课的平均分
a=list(sympy.symbols('A:E'))
mean=list(sympy.symbols('mean:{}'.format(len(A[0]))))
max=list(sympy.symbols('max:{}'.format(len(A[0]))))
min=list(sympy.symbols('min:{}'.format(len(A[0]))))
for j in range(len(A[0])):
    sum=0
    Amax=A[0,j]
    Amin=A[0,j]
    for i in range(len(A)):
        sum+= A[i,j]/ len(A)
        if A[i,j] > Amax:
            Amax= A[i,j]
        elif A[i,j] < Amin:
            Amin= A[i,j]
    mean[j]=sum
    max[j]=Amax
    min[j]=Amin
pl=[print("科目{}的平均分：{}，最高分：{}，最低分：{}".format(a[j], mean[j], max[j], min[j])) for j in range(len(A[0]))]

同学1的平均分：78.2，最高分：83，最低分：75
同学2的平均分：85.4，最高分：98，最低分：70
同学3的平均分：88.0，最高分：95，最低分：75
同学4的平均分：80.4，最高分：88，最低分：70

科目A的平均分：89.0，最高分：98，最低分：80
科目B的平均分：72.5，最高分：75，最低分：70
科目C的平均分：83.0，最高分：90，最低分：75
科目D的平均分：83.0，最高分：90，最低分：78
科目E的平均分：87.5，最高分：95，最低分：82


In [95]:
#Numpy函数法
import sympy as sp
import numpy as np
import pandas as pd
A=np.array([[80,75,75,78,83],[98,70,85,84,90],[90,75,90,90,95],[88,70,82,80,82]])

stu_mean= A.mean(1)
stu_max= A.max(1)
stu_min= A.min(1)
stu= [print("学生{}的平均分：{}， 最高分：{}， 最低分：{}".format((i+1), stu_mean[i], stu_max[i], stu_min[i])) for i in range(len(stu_mean))]

print()
sym_les= sp.symbols("A:E")
les_mean= A.mean(0)
les_max= A.max(0)
les_min= A.min(0)
les= [print("科目{}的平均分：{}， 最高分：{}， 最低分：{}".format(sym_les[i], les_mean[i], les_max[i], les_min[i])) for i in range(len(les_mean))]

学生1的平均分：78.2， 最高分：83， 最低分：75
学生2的平均分：85.4， 最高分：98， 最低分：70
学生3的平均分：88.0， 最高分：95， 最低分：75
学生4的平均分：80.4， 最高分：88， 最低分：70

科目A的平均分：89.0， 最高分：98， 最低分：80
科目B的平均分：72.5， 最高分：75， 最低分：70
科目C的平均分：83.0， 最高分：90， 最低分：75
科目D的平均分：83.0， 最高分：90， 最低分：78
科目E的平均分：87.5， 最高分：95， 最低分：82


---
#### ex 5.16
表1 不同商店3种水果的价格
|商店水果价格|商店A|商店B|
|:---:|:---:|:---:|
|苹果|8.5|9|
|橘子|4.5|4|
|梨|9|9.5|

表2 不同人员需要水果的数量
|人员需要水果数量|苹果|橘子|梨|
|:---:|:---:|:---:|:---:|
|人员A|5|10|3|
|人员B|4|5|5|

表3 不同城镇不同人员的数目
|城镇人员数目|人员A|人员B|
|:---:|:---:|:---:|
|城镇1|1000|500|
|城镇2|2000|1000|

1. 计算在每个商店中每个人购买水果的费用
2. 计算在每个城镇中每种水果的购买量

In [59]:
import numpy as np

A=np.matrix([[8.5, 9], [4.5, 4] , [9, 9.5]])
B=np.matrix([[5, 10, 3], [4, 5, 5]])
C=np.matrix([[1000, 500], [2000, 1000]])

#1
D= B.dot(A)
print("每个商店中每个人购买水果的费用:\n{}".format(D))

#2
E=C.dot(B)
print("计算在每个城镇中每种水果的购买量\n{}".format(E))

每个商店中每个人购买水果的费用:
[[114.5 113.5]
 [101.5 103.5]]
计算在每个城镇中每种水果的购买量
[[ 7000 12500  5500]
 [14000 25000 11000]]


---
#### ex 5.17  
将某线性系统用下面的线性方程组表示，求未知量$x$、$y$、$z$，并验证结果
$$\left\{\begin{matrix}
  x+2y+z=7 \\
  2x-y+3z=7 \\
  3x+y+2z=18
\end{matrix}\right.$$

In [60]:
import numpy as np

#定义 
A= np.matrix([[1, 2, 1], [2, -1, 3], [3, 1, 2]])    #系数矩阵
B= np.matrix([7, 7, 18]).T  #常数项矩阵

#求系数矩阵A的秩 和 增广矩阵(A,B)的秩
AB= np.hstack((A,B))
print("系数矩阵A的秩：{}\n增广矩阵(A,B)的秩：{}".format(np.linalg.matrix_rank(A), np.linalg.matrix_rank(AB)))
print("增广矩阵(A,B)：\n{}".format(AB))


系数矩阵A的秩：3
增广矩阵(A,B)的秩：3
增广矩阵(A,B)：
[[ 1  2  1  7]
 [ 2 -1  3  7]
 [ 3  1  2 18]]


In [61]:
#方法一：
print("方法一")
#未知数矩阵X = 系数矩阵A的逆矩阵 * 常数项矩阵
A_inv= np.linalg.inv(A)
X= A_inv.dot(B)
print("未知数矩阵X：\n{}".format(X))

#用allclose()函数检验
print("B和A*X是否相等：{}".format(np.allclose(B,A.dot(X))))

方法一
未知数矩阵X：
[[ 7.]
 [ 1.]
 [-2.]]
B和A*X是否相等：True


In [62]:
#方法二：
print("方法二：")
#np.linalg.solve()
X= np.linalg.solve(A, B)    #A必须是非奇异矩阵
print("未知数矩阵X：\n{}".format(X))

#验证
print("B和A*X是否相等：{}".format(np.allclose(B,A.dot(X))))

方法二：
未知数矩阵X：
[[ 7.]
 [ 1.]
 [-2.]]
B和A*X是否相等：True


In [63]:
#方法三：
print("方法三：")
#Sympy库的solve()函数
from sympy import *
x, y, z= symbols('x,y,z')
eq= [x+2*y+z-7, 2*x-y+3*z-7, 3*x+y+2*z-18]
solution= solve(eq, [x, y, z])
print("结果：{}".format(solution))

方法三：
结果：{x: 7, y: 1, z: -2}


解方程
$$\left\{\begin{matrix}
  x+2y+z-2w=0 \\
  2x+3y-w=0 \\
  x-y-5z+7w=0
\end{matrix}\right.$$

In [64]:
import numpy as np

#定义
A= np.matrix([[1, 2, 1, -2], [2, 3, 0, -1], [1, -1, -5, 7]])    #系数矩阵
print("系数矩阵A的秩：{}".format(np.linalg.matrix_rank(A)))

系数矩阵A的秩：2


In [65]:
from sympy import *

x, y, z, w= symbols('x,y,z,w')
eq= [x+2*y+z-2*w, 2*x+3*y-w, x-y-5*z+7*w]
solution= solve(eq, [x, y, z, w])
print("结果是：{}".format(solution))

#赋值
A={z:1, w:2}
x= float(solution[x].subs(A))
y= float(solution[y].subs(A))
print("x={}, y={}, z={}, w={}".format(x, y, A[z], A[w]))

结果是：{x: -4*w + 3*z, y: 3*w - 2*z}
x=-5.0, y=4.0, z=1, w=2


---
#### ex 5.18  
**获取数据集的数据**

1. 从文件中读入数据

2. 将数据转化成矩阵的形式

3. 对样本数据和类别标签进行分离

In [66]:
#方法1：用pandas导入文本文件
import pandas as pd
import numpy as np

# 读取文件
dataset= pd.read_csv("iris.csv")

# 将数据转化为矩阵的形式
data= np.array(dataset)

# 获取数据和标签
X_data= data[:,:-1]
Y_data= data[:,-1]

#(查看相关信息)
print("数据集中的样本数为{}，列数为{}".format(data.shape[0], data.shape[1]))
data_0= X_data[0]
print("数据集的第0个样本\n{}".format(data_0))
print("数据集的属性值类型：{}".format(type(X_data[1,0])))
print("数据集的类型标签值类型：{}".format(type(Y_data[1])))

数据集中的样本数为150，列数为5
数据集的第0个样本
[5.8 4.1 1.6 0.1]
数据集的属性值类型：<class 'float'>
数据集的类型标签值类型：<class 'str'>


In [67]:
#方法二： 用Numpy的loadtxt()函数或者genfromtxt()函数
#genfromtxt()函数：面向结构化数组和确实数据
#loadtxt()函数：默认读入的数据类型是float，如果数据中存在str，则需要让参数dtype=np.str;参数skiprows设置数据从哪行开始
import numpy as np

# 读取文件
data= np.loadtxt('iris.csv', delimiter=",", dtype=np.str_, skiprows=1)  #不保留标题行

# 获取数据和标签
X_data= data[:,:-1].astype('float') #如果保留标题行，行数从1开始
Y_data= data[:,-1]

#(查看相关信息)
print("数据集中的样本数为{}，列数为{}".format(data.shape[0], data.shape[1]))
data_0= X_data[0]
print("数据集的第0个样本\n{}".format(data_0))
print("数据集的属性值类型：{}".format(type(X_data[1,0])))
print("数据集的类型标签值类型：{}".format(type(Y_data[1])))

数据集中的样本数为150，列数为5
数据集的第0个样本
[5.8 4.1 1.6 0.1]
数据集的属性值类型：<class 'numpy.float64'>
数据集的类型标签值类型：<class 'numpy.str_'>


In [68]:
#方法3： 原始方式
import numpy as np

# 读取数据
dataset= [(line.split(',') ) for line in open("iris.csv")]

# 将数据转化为矩阵的形式
data= np.array(dataset)

# 获取数据和标签
X_data= np.array([[float(x) for x in line[:-1]] for line in data[1:]])
Y_data= np.array([x.strip('\n') for x in data[1:,-1]])

#(查看相关信息)
print("数据集中的样本数为{}，列数为{}".format(data.shape[0], data.shape[1]))
data_0= X_data[0]
print("数据集的第0个样本\n{}".format(data_0))
print("数据集的属性值类型：{}".format(type(X_data[1,0])))
print("数据集的类型标签值类型：{}".format(type(Y_data[1])))

数据集中的样本数为151，列数为5
数据集的第0个样本
[5.8 4.1 1.6 0.1]
数据集的属性值类型：<class 'numpy.float64'>
数据集的类型标签值类型：<class 'numpy.str_'>


---
---
---
### 课后习题

#### 1. 分别用三种方法求如下线性方程组的解  
$$\left\{\begin{matrix}
 x+y+z=2\\
 x+2y+4z=3\\
 x+3y+9z=5
\end{matrix}\right.$$

In [103]:
import numpy as np
A= np.matrix([[1, 1, 1], [1, 2, 4], [1, 3, 9]])
B= np.matrix([2, 3, 5]).T
AB= np.hstack((A, B))
print("系数矩阵A和增广矩阵的(A,B)的秩是否相等：{}".format((np.linalg.matrix_rank(A))==(np.linalg.matrix_rank(AB))))

系数矩阵A和增广矩阵的(A,B)的秩是否相等：True


In [106]:
#方法一
A_inv= np.linalg.inv(A)
X =A_inv.dot(B)
print("X=A_inv*B=\n{}".format(X))
print("验证A*X是否等于B：{}".format(np.allclose(A.dot(X), B)))

X=A_inv*B=
[[ 2. ]
 [-0.5]
 [ 0.5]]
验证A*X是否等于B：True


In [107]:
#方法二：
X= np.linalg.solve(A, B)
print("X=A_inv*B=\n{}".format(X))
print("验证A*X是否等于B：{}".format(np.allclose(A.dot(X), B)))

X=A_inv*B=
[[ 2. ]
 [-0.5]
 [ 0.5]]
验证A*X是否等于B：True


$$\left\{\begin{matrix}
 x+y+z=2\\
 x+2y+4z=3\\
 x+3y+9z=5
\end{matrix}\right.$$

In [110]:
#方法三：
from sympy import *

x, y, z= symbols('x:z')
eq= [x+y+z-2, x+2*y+4*z-3, x+3*y+9*z-5]
solution= solve(eq, [x, y, z])
print("x={}, y={}, z={}".format(solution[x], solution[y], solution[z]))

x=2, y=-1/2, z=1/2


---
#### ２. 分别创建 $3\times4$ 阶和 $4\times5$ 阶的矩阵，元素值为 $1$~$20$ 的随机整数，计算这两个矩阵的相加、乘积，求这两个矩阵的秩

In [54]:
import numpy as np

A= np.random.randint(1, 20, (3,4))
B= np.random.randint(1, 20, (4,5))
if A.shape == B.shape:
    AB_and= A + B
else:
    AB_and= None
AB_mul= A.dot(B)
rank_A= np.linalg.matrix_rank(A)
rank_B= np.linalg.matrix_rank(B)
print("A=\n{}\nB=\n{}\nA+B={}\nA*B=\n{}\nrank_A={}\nrank_B={}".format(A, B, AB_and, AB_mul, rank_A, rank_B))

A=
[[ 8  5  4 16]
 [11 17 19 19]
 [13 14  7  7]]
B=
[[ 4 14 19  9 16]
 [17  1 12 13 11]
 [18 18  8 17 14]
 [12 10 12 11  1]]
A+B=None
A*B=
[[381 349 436 381 255]
 [903 703 793 852 648]
 [500 392 555 495 467]]
rank_A=3
rank_B=4


---
#### 3. 求下面矩阵的逆矩阵，求逆矩阵之前要先求行列式，行列式不为0时逆矩阵存在，之后在进行求逆操作。  
$$\bf A=\begin{bmatrix}
 1 & 2 & 3\\
 2 & 2 & 1\\
 3 & 4 & 3
\end{bmatrix}$$

In [61]:
import numpy as np

A= np.matrix([[1, 2, 3], [2, 2, 1], [3, 4, 3]])
det_A= np.linalg.det(A)
print("A的逆矩阵是否存在：{}".format(det_A!=0))
A_inv= np.linalg.inv(A)
print("A的逆矩阵为：\n{}".format(A_inv))
print("验证：{}".format(np.allclose(A.dot(A_inv), np.eye(A.shape[0],A.shape[1]))))

A的逆矩阵是否存在：True
A的逆矩阵为：
[[ 1.   3.  -2. ]
 [-1.5 -3.   2.5]
 [ 1.   1.  -1. ]]
验证：True


---
#### 4. 分别创建四阶零矩阵和四阶单位矩阵，以及对角线元素分别为 $1, 2, 3, 4$ 的对角矩阵。

In [68]:
import numpy as np

Zero= np.zeros((4,4))
Eye= np.eye(4)
Diag= np.diag([1, 2, 3, 4])
print("四阶零矩阵：\n{}\n四阶单位矩阵：\n{}\n对角矩阵：\n{}".format(Zero, Eye, Diag))

四阶零矩阵：
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
四阶单位矩阵：
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
对角矩阵：
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


---
#### 5. 创建一个四阶方阵，元素值为 $1$~$20$ 的随机浮点数，根据其上三角和下三角矩阵，分别创建对应的对称矩阵。

In [105]:
import numpy as np

A=np.random.uniform(1, 20, (4,4))
A_u0= np.triu(A)
A_u1= np.triu(A, k=1)
A_symu= A_u0 + A_u1.T

A_l0= np.tril(A)
A_l1= np.tril(A, k=-1)
A_syml= A_l0 + A_l1.T

print("上三角矩阵的对称矩阵：\n{}\n下三角矩阵的对称矩阵：\n{}".format(A_symu, A_syml))

上三角矩阵的对称矩阵：
[[ 8.65665363 14.50521017  9.99025207 10.69112443]
 [14.50521017 11.23272485  3.01849015 12.41810065]
 [ 9.99025207  3.01849015 16.08408762 13.88100402]
 [10.69112443 12.41810065 13.88100402 13.43689347]]
下三角矩阵的对称矩阵：
[[ 8.65665363 10.62193845 14.92407263  1.28103483]
 [10.62193845 11.23272485 16.6070416  18.33634152]
 [14.92407263 16.6070416  16.08408762 18.19060746]
 [ 1.28103483 18.33634152 18.19060746 13.43689347]]
